In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/feature_engineered_data.csv"
)

df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,invoiceno_length,stockcode_length,description_length,invoicedate_length,country_length
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,6,6,34,19,14
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,5,19,19,14
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,6,6,30,19,14
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,35,19,14
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,30,19,14

In [3]:
df.shape

(536641, 13)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 536641 entries, 0 to 536640
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   invoiceno           536641 non-null  str
 1   stockcode           536641 non-null  str
 2   description         536641 non-null  str
 3   quantity            536641 non-null  int64
 4   invoicedate         536641 non-null  str
 5   unitprice           536641 non-null  float64
 6   customerid          536641 non-null  float64
 7   country             536641 non-null  str
 8   invoiceno_length    536641 non-null  int64
 9   stockcode_length    536641 non-null  int64
 10  description_length  536641 non-null  int64
 11  invoicedate_length  536641 non-null  int64
 12  country_length      536641 non-null  int64
dtypes: float64(2), int64(6), str(5)
memory usage: 53.2 MB

In [5]:
def generate_basic_kpis(df):

    kpis = {}

    kpis["total_rows"] = len(df)
    kpis["total_columns"] = len(df.columns)
    kpis["duplicate_rows"] = df.duplicated().sum()
    kpis["total_missing_values"] = df.isnull().sum().sum()

    numeric_columns = df.select_dtypes(
        include="number"
    ).columns

    categorical_columns = df.select_dtypes(
        include=["object", "string", "category"]
    ).columns

    kpis["numeric_columns"] = len(numeric_columns)
    kpis["categorical_columns"] = len(categorical_columns)

    return kpis

In [6]:
kpis = generate_basic_kpis(df)

kpis

{'total_rows': 536641,
 'total_columns': 13,
 'duplicate_rows': np.int64(0),
 'total_missing_values': np.int64(0),
 'numeric_columns': 8,
 'categorical_columns': 5}

In [7]:
numeric_columns = df.select_dtypes(
    include="number"
).columns.tolist()

numeric_columns

['quantity',
 'unitprice',
 'customerid',
 'invoiceno_length',
 'stockcode_length',
 'description_length',
 'invoicedate_length',
 'country_length']

In [8]:
numeric_kpis = {}

for col in numeric_columns:

    numeric_kpis[col] = {
        "mean": df[col].mean(),
        "median": df[col].median(),
        "minimum": df[col].min(),
        "maximum": df[col].max(),
        "sum": df[col].sum()
    }

In [9]:
numeric_kpis

{'quantity': {'mean': np.float64(9.620029032444409),
  'median': np.float64(3.0),
  'minimum': np.int64(-80995),
  'maximum': np.int64(80995),
  'sum': np.int64(5162502)},
 'unitprice': {'mean': np.float64(4.632655674836623),
  'median': np.float64(2.08),
  'minimum': np.float64(-11062.06),
  'maximum': np.float64(38970.0),
  'sum': np.float64(2486072.974)},
 'customerid': {'mean': np.float64(15246.898157241061),
  'median': np.float64(15145.0),
  'minimum': np.float64(12346.0),
  'maximum': np.float64(18287.0),
  'sum': np.float64(8182110674.0)},
 'invoiceno_length': {'mean': np.float64(6.017244302988404),
  'median': np.float64(6.0),
  'minimum': np.int64(6),
  'maximum': np.int64(7),
  'sum': np.int64(3229100)},
 'stockcode_length': {'mean': np.float64(5.087033976159108),
  'median': np.float64(5.0),
  'minimum': np.int64(1),
  'maximum': np.int64(12),
  'sum': np.int64(2729911)},
 'description_length': {'mean': np.float64(26.442865901039987),
  'median': np.float64(27.0),
  'minimum': np.int64(1),
  'maximum': np.int64(35),
  'sum': np.int64(14190326)},
 'invoicedate_length': {'mean': np.float64(19.0),
  'median': np.float64(19.0),
  'minimum': np.int64(19),
  'maximum': np.int64(19),
  'sum': np.int64(10196179)},
 'country_length': {'mean': np.float64(13.371257507346625),
  'median': np.float64(14.0),
  'minimum': np.int64(3),
  'maximum': np.int64(20),
  'sum': np.int64(7175565)}}

In [10]:
categorical_columns = df.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

categorical_columns

['invoiceno', 'stockcode', 'description', 'invoicedate', 'country']

In [11]:
for col in categorical_columns:

    print("\nColumn:", col)
    print(df[col].value_counts().head(10))

Column: invoiceno
invoiceno
573585    1114
581219     749
581492     731
580729     721
558475     705
579777     687
581217     676
537434     675
580730     662
538071     652
Name: count, dtype: int64

Column: stockcode
stockcode
85123A    2301
22423     2192
85099B    2156
47566     1720
20725     1626
84879     1489
22720     1469
22197     1468
21212     1367
22383     1328
Name: count, dtype: int64

Column: description
description
WHITE HANGING HEART T-LIGHT HOLDER    3811
REGENCY CAKESTAND 3 TIER              2189
JUMBO BAG RED RETROSPOT               2156
PARTY BUNTING                         1720
LUNCH BAG RED RETROSPOT               1625
ASSORTED COLOUR BIRD ORNAMENT         1488
SET OF 3 CAKE TINS PANTRY DESIGN      1465
PACK OF 72 RETROSPOT CAKE CASES       1367
LUNCH BAG  BLACK SKULL.               1323
NATURAL SLATE HEART CHALKBOARD        1272
Name: count, dtype: int64

Column: invoicedate
invoicedate
2011-10-31 14:41:00    1114
2011-12-08 09:28:00     749
2011-12-09 10:03:00     731
2011-12-05 17:24:00     721
2011-06-29 15:58:00     705
2011-11-30 15:13:00     687
2011-12-08 09:20:00     676
2010-12-06 16:57:00     675
2011-12-05 17:28:00     662
2010-12-09 14:09:00     652
Name: count, dtype: int64

Column: country
country
United Kingdom    490300
Germany             9480
France              8541
EIRE                8184
Spain               2528
Netherlands         2371
Belgium             2069
Switzerland         1994
Portugal            1510
Australia           1258
Name: count, dtype: int64

In [12]:
def get_top_categories(df, top_n=5):

    results = {}

    categorical_columns = df.select_dtypes(
        include=["object", "string", "category"]
    ).columns

    for col in categorical_columns:

        results[col] = (
            df[col]
            .value_counts()
            .head(top_n)
            .to_dict()
        )

    return results

In [13]:
top_categories = get_top_categories(df)

top_categories

{'invoiceno': {'573585': 1114,
  '581219': 749,
  '581492': 731,
  '580729': 721,
  '558475': 705},
 'stockcode': {'85123A': 2301,
  '22423': 2192,
  '85099B': 2156,
  '47566': 1720,
  '20725': 1626},
 'description': {'WHITE HANGING HEART T-LIGHT HOLDER': 3811,
  'REGENCY CAKESTAND 3 TIER': 2189,
  'JUMBO BAG RED RETROSPOT': 2156,
  'PARTY BUNTING': 1720,
  'LUNCH BAG RED RETROSPOT': 1625},
 'invoicedate': {'2011-10-31 14:41:00': 1114,
  '2011-12-08 09:28:00': 749,
  '2011-12-09 10:03:00': 731,
  '2011-12-05 17:24:00': 721,
  '2011-06-29 15:58:00': 705},
 'country': {'United Kingdom': 490300,
  'Germany': 9480,
  'France': 8541,
  'EIRE': 8184,
  'Spain': 2528}}

In [14]:
date_columns = df.select_dtypes(
    include=["datetime"]
).columns.tolist()

date_columns

[]

In [15]:
for col in date_columns:

    print("Date Column:", col)
    print("Start Date:", df[col].min())
    print("End Date:", df[col].max())

In [16]:
def generate_insights(df):

    insights = []

    # Dataset size
    insights.append(
        f"Dataset contains {len(df)} rows and {len(df.columns)} columns."
    )

    # Missing values
    missing = df.isnull().sum().sum()

    if missing > 0:
        insights.append(
            f"Dataset contains {missing} missing values."
        )
    else:
        insights.append(
            "Dataset contains no missing values."
        )

    # Duplicate values
    duplicates = df.duplicated().sum()

    if duplicates > 0:
        insights.append(
            f"Dataset contains {duplicates} duplicate rows."
        )
    else:
        insights.append(
            "No duplicate rows were detected."
        )

    # Numeric columns
    numeric_columns = df.select_dtypes(
        include="number"
    ).columns.tolist()

    insights.append(
        f"Dataset contains {len(numeric_columns)} numeric columns."
    )

    # Categorical columns
    categorical_columns = df.select_dtypes(
        include=["object", "string", "category"]
    ).columns.tolist()

    insights.append(
        f"Dataset contains {len(categorical_columns)} categorical columns."
    )

    return insights

In [17]:
insights = generate_insights(df)

for insight in insights:
    print("•", insight)

• Dataset contains 536641 rows and 13 columns.
• Dataset contains no missing values.
• No duplicate rows were detected.
• Dataset contains 8 numeric columns.
• Dataset contains 5 categorical columns.

In [18]:
if "quantity" in df.columns and "unitprice" in df.columns:

    df["sales"] = (
        df["quantity"] * df["unitprice"]
    )

    print("Total Sales:", df["sales"].sum())

Total Sales: 9726006.954

In [20]:
kpi_table = pd.DataFrame({
    "KPI": [
        "Total Rows",
        "Total Columns",
        "Duplicate Rows",
        "Missing Values",
        "Numeric Columns",
        "Categorical Columns"
    ],

    "Value": [
        len(df),
        len(df.columns),
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        len(df.select_dtypes(include="number").columns),
        len(df.select_dtypes(
            include=["object", "string", "category"]
        ).columns)
    ]
})

kpi_table

                   KPI   Value
0           Total Rows  536641
1        Total Columns      14
2       Duplicate Rows       0
3       Missing Values       0
4      Numeric Columns       9
5  Categorical Columns       5

In [21]:
kpi_table.to_csv(
    "../data/processed/kpi_report.csv",
    index=False
)

In [22]:
pd.read_csv(
    "../data/processed/kpi_report.csv"
)

                   KPI   Value
0           Total Rows  536641
1        Total Columns      14
2       Duplicate Rows       0
3       Missing Values       0
4      Numeric Columns       9
5  Categorical Columns       5

In [23]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.insights.kpi_engine import (
    generate_basic_kpis,
    generate_numeric_kpis,
    get_top_categories,
    generate_insights
)

In [24]:
kpis = generate_basic_kpis(df)

kpis

{'total_rows': 536641,
 'total_columns': 14,
 'duplicate_rows': np.int64(0),
 'total_missing_values': np.int64(0),
 'numeric_columns': 9,
 'categorical_columns': 5}

In [25]:
numeric_kpis = generate_numeric_kpis(df)

numeric_kpis

{'quantity': {'mean': np.float64(9.620029032444409),
  'median': np.float64(3.0),
  'minimum': np.int64(-80995),
  'maximum': np.int64(80995),
  'sum': np.int64(5162502)},
 'unitprice': {'mean': np.float64(4.632655674836623),
  'median': np.float64(2.08),
  'minimum': np.float64(-11062.06),
  'maximum': np.float64(38970.0),
  'sum': np.float64(2486072.974)},
 'customerid': {'mean': np.float64(15246.898157241061),
  'median': np.float64(15145.0),
  'minimum': np.float64(12346.0),
  'maximum': np.float64(18287.0),
  'sum': np.float64(8182110674.0)},
 'invoiceno_length': {'mean': np.float64(6.017244302988404),
  'median': np.float64(6.0),
  'minimum': np.int64(6),
  'maximum': np.int64(7),
  'sum': np.int64(3229100)},
 'stockcode_length': {'mean': np.float64(5.087033976159108),
  'median': np.float64(5.0),
  'minimum': np.int64(1),
  'maximum': np.int64(12),
  'sum': np.int64(2729911)},
 'description_length': {'mean': np.float64(26.442865901039987),
  'median': np.float64(27.0),
  'minimum': np.int64(1),
  'maximum': np.int64(35),
  'sum': np.int64(14190326)},
 'invoicedate_length': {'mean': np.float64(19.0),
  'median': np.float64(19.0),
  'minimum': np.int64(19),
  'maximum': np.int64(19),
  'sum': np.int64(10196179)},
 'country_length': {'mean': np.float64(13.371257507346625),
  'median': np.float64(14.0),
  'minimum': np.int64(3),
  'maximum': np.int64(20),
  'sum': np.int64(7175565)},
 'sales': {'mean': np.float64(18.1238611175814),
  'median': np.float64(9.870000000000001),
  'minimum': np.float64(-168469.6),
  'maximum': np.float64(168469.6),
  'sum': np.float64(9726006.954)}}

In [26]:
top_categories = get_top_categories(df)

top_categories

{'invoiceno': {'573585': 1114,
  '581219': 749,
  '581492': 731,
  '580729': 721,
  '558475': 705},
 'stockcode': {'85123A': 2301,
  '22423': 2192,
  '85099B': 2156,
  '47566': 1720,
  '20725': 1626},
 'description': {'WHITE HANGING HEART T-LIGHT HOLDER': 3811,
  'REGENCY CAKESTAND 3 TIER': 2189,
  'JUMBO BAG RED RETROSPOT': 2156,
  'PARTY BUNTING': 1720,
  'LUNCH BAG RED RETROSPOT': 1625},
 'invoicedate': {'2011-10-31 14:41:00': 1114,
  '2011-12-08 09:28:00': 749,
  '2011-12-09 10:03:00': 731,
  '2011-12-05 17:24:00': 721,
  '2011-06-29 15:58:00': 705},
 'country': {'United Kingdom': 490300,
  'Germany': 9480,
  'France': 8541,
  'EIRE': 8184,
  'Spain': 2528}}

In [27]:
insights = generate_insights(df)

for insight in insights:
    print("•", insight)

• Dataset contains 536641 rows and 14 columns.
• Dataset contains no missing values.
• No duplicate rows were detected.
• Dataset contains 9 numeric columns.
• Dataset contains 5 categorical columns.

In [28]:
import pandas as pd

raw_df = pd.read_excel(
    "../data/raw/Online Retail.xlsx"
)

cleaned_df = pd.read_csv(
    "../data/processed/cleaned_data.csv"
)

feature_df = pd.read_csv(
    "../data/processed/feature_engineered_data.csv"
)

print("Raw Data:", raw_df.shape)
print("Cleaned Data:", cleaned_df.shape)
print("Feature Engineered Data:", feature_df.shape)

Raw Data: (541909, 8)
Cleaned Data: (536641, 8)
Feature Engineered Data: (536641, 13)

In [29]:
kpi_df = pd.read_csv(
    "../data/processed/kpi_report.csv"
)

kpi_df

                   KPI   Value
0           Total Rows  536641
1        Total Columns      14
2       Duplicate Rows       0
3       Missing Values       0
4      Numeric Columns       9
5  Categorical Columns       5

In [30]:
feature_df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,invoiceno_length,stockcode_length,description_length,invoicedate_length,country_length
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,6,6,34,19,14
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,5,19,19,14
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,6,6,30,19,14
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,35,19,14
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,30,19,14

In [31]:
feature_df.columns.tolist()

['invoiceno',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'unitprice',
 'customerid',
 'country',
 'invoiceno_length',
 'stockcode_length',
 'description_length',
 'invoicedate_length',
 'country_length']

In [32]:
kpi_df = pd.read_csv(
    "../data/processed/kpi_report.csv"
)

kpi_df

                   KPI   Value
0           Total Rows  536641
1        Total Columns      14
2       Duplicate Rows       0
3       Missing Values       0
4      Numeric Columns       9
5  Categorical Columns       5