In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/feature_engineered_data.csv"
)

df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,invoiceno_length,stockcode_length,description_length,invoicedate_length,country_length
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,6,6,34,19,14
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,5,19,19,14
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,6,6,30,19,14
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,35,19,14
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,6,6,30,19,14

In [2]:
df.shape

(536641, 13)

In [3]:
df.columns.tolist()

['invoiceno',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'unitprice',
 'customerid',
 'country',
 'invoiceno_length',
 'stockcode_length',
 'description_length',
 'invoicedate_length',
 'country_length']

In [4]:
df.groupby("country").size()

country
Australia                 1258
Austria                    401
Bahrain                     19
Belgium                   2069
Brazil                      32
Canada                     151
Channel Islands            757
Cyprus                     611
Czech Republic              30
Denmark                    389
EIRE                      8184
European Community          61
Finland                    695
France                    8541
Germany                   9480
Greece                     146
Hong Kong                  284
Iceland                    182
Israel                     294
Italy                      803
Japan                      358
Lebanon                     45
Lithuania                   35
Malta                      127
Netherlands               2371
Norway                    1086
Poland                     341
Portugal                  1510
RSA                         58
Saudi Arabia                10
Singapore                  229
Spain                     2528
Sweden                     461
Switzerland               1994
USA                        291
United Arab Emirates        68
United Kingdom          490300
Unspecified                442
dtype: int64

In [11]:
df.groupby("country").size().sort_values(
    ascending=False
).head(10)

country
United Kingdom    490300
Germany             9480
France              8541
EIRE                8184
Spain               2528
Netherlands         2371
Belgium             2069
Switzerland         1994
Portugal            1510
Australia           1258
dtype: int64

In [14]:
country_quantity = (
    df.groupby("country")["quantity"]
    .sum()
    .sort_values(ascending=False)
)

country_quantity.head(10)

country
United Kingdom    4250328
Netherlands        200128
EIRE               142495
Germany            117341
France             110438
Australia           83643
Sweden              35632
Switzerland         30313
Spain               26817
Japan               25218
Name: quantity, dtype: int64

In [16]:
country_analysis = (
    df.groupby("country")
    .agg(
        total_quantity=("quantity", "sum"),
        average_quantity=("quantity", "mean"),
        average_price=("unitprice", "mean"),
        transactions=("invoiceno", "nunique")
    )
    .sort_values(
        "total_quantity",
        ascending=False
    )
)

country_analysis.head(10)

                total_quantity  average_quantity  average_price  transactions
country
United Kingdom         4250328          8.668831       4.554859         23494
Netherlands             200128         84.406580       2.738317           101
EIRE                    142495         17.411413       5.914024           360
Germany                 117341         12.377743       3.969772           603
France                  110438         12.930336       5.032898           461
Australia                83643         66.488871       3.217806            69
Sweden                   35632         77.292842       3.914816            46
Switzerland              30313         15.202106       3.408019            74
Spain                    26817         10.607991       4.992682           105
Japan                    25218         70.441341       2.276145            28

In [17]:
country_analysis.sort_values(
    "transactions",
    ascending=False
).head(10)

                total_quantity  average_quantity  average_price  transactions
country
United Kingdom         4250328          8.668831       4.554859         23494
Germany                 117341         12.377743       3.969772           603
France                  110438         12.930336       5.032898           461
EIRE                    142495         17.411413       5.914024           360
Belgium                  23152         11.189947       3.644335           119
Spain                    26817         10.607991       4.992682           105
Netherlands             200128         84.406580       2.738317           101
Switzerland              30313         15.202106       3.408019            74
Portugal                 16153         10.697351       8.616510            71
Australia                83643         66.488871       3.217806            69

In [18]:
country_analysis.sort_values(
    "transactions",
    ascending=True
).head(10)

,total_quantity,average_quantity,average_price,transactions
country,,,,
Brazil,356,11.125000,4.456250,1
RSA,352,6.068966,4.277586,1
Lebanon,386,8.577778,5.387556,1
Saudi Arabia,75,7.500000,2.411000,2
United Arab Emirates,982,14.441176,3.380735,3
Lithuania,652,18.628571,2.841143,4
Bahrain,260,13.684211,4.556316,4
Czech Republic,592,19.733333,2.938333,5
European Community,497,8.147541,4.820492,5
Canada,2763,18.298013,6.030331,6

In [20]:
pivot = pd.pivot_table(
    df,
    values="quantity",
    index="country",
    aggfunc="sum"
)

pivot.sort_values(
    "quantity",
    ascending=False
).head(10)

                quantity
country
United Kingdom   4250328
Netherlands       200128
EIRE              142495
Germany           117341
France            110438
Australia          83643
Sweden             35632
Switzerland        30313
Spain              26817
Japan              25218

In [21]:
df.columns.tolist()

['invoiceno',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'unitprice',
 'customerid',
 'country',
 'invoiceno_length',
 'stockcode_length',
 'description_length',
 'invoicedate_length',
 'country_length']

In [24]:
monthly_quantity = (
    df.groupby(
        ["InvoiceDate_year", "InvoiceDate_month"]
    )["quantity"]
    .sum()
)

monthly_quantity

KeyError: 'InvoiceDate_year'

In [25]:
country_analysis["rank"] = (
    country_analysis["total_quantity"]
    .rank(
        ascending=False,
        method="dense"
    )
)

country_analysis.head(10)

,total_quantity,average_quantity,average_price,transactions,rank
country,,,,,
United Kingdom,4250328,8.668831,4.554859,23494,1.0
Netherlands,200128,84.406580,2.738317,101,2.0
EIRE,142495,17.411413,5.914024,360,3.0
Germany,117341,12.377743,3.969772,603,4.0
France,110438,12.930336,5.032898,461,5.0
Australia,83643,66.488871,3.217806,69,6.0
Sweden,35632,77.292842,3.914816,46,7.0
Switzerland,30313,15.202106,3.408019,74,8.0
Spain,26817,10.607991,4.992682,105,9.0
Japan,25218,70.441341,2.276145,28,10.0

In [27]:
total_quantity = df["quantity"].sum()

In [29]:
country_analysis["contribution_percent"] = (
    country_analysis["total_quantity"]
    / total_quantity
    * 100
)

In [30]:
country_analysis.head(10)

,total_quantity,average_quantity,average_price,transactions,rank,contribution_percent
country,,,,,,
United Kingdom,4250328,8.668831,4.554859,23494,1.0,82.330777
Netherlands,200128,84.406580,2.738317,101,2.0,3.876570
EIRE,142495,17.411413,5.914024,360,3.0,2.760193
Germany,117341,12.377743,3.969772,603,4.0,2.272948
France,110438,12.930336,5.032898,461,5.0,2.139234
Australia,83643,66.488871,3.217806,69,6.0,1.620203
Sweden,35632,77.292842,3.914816,46,7.0,0.690208
Switzerland,30313,15.202106,3.408019,74,8.0,0.587177
Spain,26817,10.607991,4.992682,105,9.0,0.519457
Japan,25218,70.441341,2.276145,28,10.0,0.488484

In [31]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [32]:
from src.analytics.pandas_analysis import (
    group_and_aggregate,
    get_top_values,
    get_numeric_summary,
    calculate_percentage
)

In [34]:
top_countries = get_top_values(
    df,
    "country",
    10
)

top_countries

country
United Kingdom    490300
Germany             9480
France              8541
EIRE                8184
Spain               2528
Netherlands         2371
Belgium             2069
Switzerland         1994
Portugal            1510
Australia           1258
Name: count, dtype: int64

In [37]:
result = group_and_aggregate(
    df,
    "country",
    {
        "quantity": "sum",
        "unitprice": "mean"
    }
)

result.head()

     country  quantity  unitprice
0  Australia     83643   3.217806
1    Austria      4827   4.243192
2    Bahrain       260   4.556316
3    Belgium     23152   3.644335
4     Brazil       356   4.456250

In [36]:
df.columns.tolist()

['invoiceno',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'unitprice',
 'customerid',
 'country',
 'invoiceno_length',
 'stockcode_length',
 'description_length',
 'invoicedate_length',
 'country_length']

In [38]:
country_analysis.to_csv(
    "../data/processed/country_analysis.csv"
)

In [39]:
pd.read_csv(
    "../data/processed/country_analysis.csv"
).head()

,country,total_quantity,average_quantity,average_price,transactions,rank,contribution_percent
0,United Kingdom,4250328,8.668831,4.554859,23494,1.0,82.330777
1,Netherlands,200128,84.406580,2.738317,101,2.0,3.876570
2,EIRE,142495,17.411413,5.914024,360,3.0,2.760193
3,Germany,117341,12.377743,3.969772,603,4.0,2.272948
4,France,110438,12.930336,5.032898,461,5.0,2.139234