In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd

from src.analytics.product_analysis import (
    detect_product_category_columns,
    analyze_product_performance,
    get_top_products,
    get_bottom_products,
    calculate_product_contribution,
    rank_products,
    analyze_category_performance,
    calculate_category_contribution,
    rank_categories,
    create_product_report,
    create_category_report,
    generate_product_insight
)

In [2]:
df_test = pd.DataFrame({
    "Product": [
        "Laptop",
        "Mobile",
        "Laptop",
        "Tablet",
        "Mobile",
        "Headphones",
        "Tablet",
        "Laptop"
    ],

    "Category": [
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Electronics",
        "Accessories",
        "Electronics",
        "Electronics"
    ],

    "Sales": [
        50000,
        30000,
        45000,
        20000,
        35000,
        10000,
        25000,
        55000
    ]
})

df_test

      Product     Category  Sales
0      Laptop  Electronics  50000
1      Mobile  Electronics  30000
2      Laptop  Electronics  45000
3      Tablet  Electronics  20000
4      Mobile  Electronics  35000
5  Headphones  Accessories  10000
6      Tablet  Electronics  25000
7      Laptop  Electronics  55000

In [ ]:
print("Rows:", len(df_test))
print("Columns:", len(df_test.columns))

df_test.info()

In [ ]:
print("Rows:", len(df_test))
print("Columns:", len(df_test.columns))

df_test.info()

In [4]:
product_sales = analyze_product_performance(
    df=df_test,
    product_column="Product",
    metric_column="Sales",
    aggregation="sum"
)

product_sales

      Product   Sales
0      Laptop  150000
1      Mobile   65000
2      Tablet   45000
3  Headphones   10000

In [5]:
product_sales = calculate_product_contribution(
    product_sales,
    "Sales"
)

product_sales

      Product   Sales  contribution_%
0      Laptop  150000           55.56
1      Mobile   65000           24.07
2      Tablet   45000           16.67
3  Headphones   10000            3.70

In [6]:
ranked_products = rank_products(
    product_sales,
    "Sales"
)

ranked_products

      Product   Sales  contribution_%  rank
0      Laptop  150000           55.56     1
1      Mobile   65000           24.07     2
2      Tablet   45000           16.67     3
3  Headphones   10000            3.70     4

In [7]:
top_products = get_top_products(
    ranked_products,
    "Sales",
    n=3
)

top_products

  Product   Sales  contribution_%  rank
0  Laptop  150000           55.56     1
1  Mobile   65000           24.07     2
2  Tablet   45000           16.67     3

In [8]:
bottom_products = get_bottom_products(
    ranked_products,
    "Sales",
    n=3
)

bottom_products

      Product  Sales  contribution_%  rank
0  Headphones  10000            3.70     4
1      Tablet  45000           16.67     3
2      Mobile  65000           24.07     2

In [9]:
product_insight = generate_product_insight(
    product_sales,
    "Product",
    "Sales"
)

print(product_insight["insight"])

Laptop is the top-performing product with 150000.00 in Sales, contributing 55.56% of total Sales. Headphones is the lowest-performing product.

In [10]:
product_insight = generate_product_insight(
    product_sales,
    "Product",
    "Sales"
)

print(product_insight["insight"])

Laptop is the top-performing product with 150000.00 in Sales, contributing 55.56% of total Sales. Headphones is the lowest-performing product.

In [11]:
category_sales = analyze_category_performance(
    df=df_test,
    category_column="Category",
    metric_column="Sales",
    aggregation="sum"
)

category_sales

      Category   Sales
0  Electronics  260000
1  Accessories   10000

In [12]:
category_sales = analyze_category_performance(
    df=df_test,
    category_column="Category",
    metric_column="Sales",
    aggregation="sum"
)

category_sales

      Category   Sales
0  Electronics  260000
1  Accessories   10000

In [13]:
category_sales = calculate_category_contribution(
    category_sales,
    "Sales"
)

category_sales

      Category   Sales  contribution_%
0  Electronics  260000            96.3
1  Accessories   10000             3.7

In [14]:
ranked_categories = rank_categories(
    category_sales,
    "Sales"
)

ranked_categories

      Category   Sales  contribution_%  rank
0  Electronics  260000            96.3     1
1  Accessories   10000             3.7     2

In [15]:
product_report = create_product_report(
    df=df_test,
    product_column="Product",
    metric_column="Sales",
    top_n=3
)

product_report

{'total_products': 4,
 'top_products':   Product   Sales  contribution_%  rank
 0  Laptop  150000           55.56     1
 1  Mobile   65000           24.07     2
 2  Tablet   45000           16.67     3,
 'bottom_products':       Product  Sales  contribution_%  rank
 0  Headphones  10000            3.70     4
 1      Tablet  45000           16.67     3
 2      Mobile  65000           24.07     2,
 'all_products':       Product   Sales  contribution_%  rank
 0      Laptop  150000           55.56     1
 1      Mobile   65000           24.07     2
 2      Tablet   45000           16.67     3
 3  Headphones   10000            3.70     4}

In [16]:
product_report["top_products"]

  Product   Sales  contribution_%  rank
0  Laptop  150000           55.56     1
1  Mobile   65000           24.07     2
2  Tablet   45000           16.67     3

In [17]:
product_report["bottom_products"]

      Product  Sales  contribution_%  rank
0  Headphones  10000            3.70     4
1      Tablet  45000           16.67     3
2      Mobile  65000           24.07     2

In [18]:
category_report = create_category_report(
    df=df_test,
    category_column="Category",
    metric_column="Sales",
    top_n=5
)

category_report

{'total_categories': 2,
 'top_categories':       Category   Sales  contribution_%  rank
 0  Electronics  260000            96.3     1
 1  Accessories   10000             3.7     2,
 'all_categories':       Category   Sales  contribution_%  rank
 0  Electronics  260000            96.3     1
 1  Accessories   10000             3.7     2}

In [19]:
category_report["top_categories"]

      Category   Sales  contribution_%  rank
0  Electronics  260000            96.3     1
1  Accessories   10000             3.7     2

In [ ]:
df = pd.read_excel(
    "../data/raw/Online Retail.xlsx"
)

df.head()

In [ ]:
df.columns.tolist()

In [ ]:
df["Revenue"] = (
    df["Quantity"] *
    df["UnitPrice"]
)

In [ ]:
df["Revenue"] = (
    df["Quantity"] *
    df["UnitPrice"]
)

In [ ]:
detected = detect_product_category_columns(
    df
)

detected

In [ ]:
product_revenue = analyze_product_performance(
    df=df,
    product_column="Description",
    metric_column="Revenue",
    aggregation="sum"
)

product_revenue.head(10)

In [ ]:
product_revenue = calculate_product_contribution(
    product_revenue,
    "Revenue"
)

product_revenue.head(10)

In [ ]:
product_revenue = calculate_product_contribution(
    product_revenue,
    "Revenue"
)

product_revenue.head(10)